name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install java
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "11"
    - name: install clojure tools
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        cli: 1.10.1.693
        lein: 2.9.1
        clj-kondo: 2022.05.31
    - name: clean diff data
      run: rm -r test/diff/ & mkdir test/diff
    - name: test
      run: lein test
    - name: check no changes
      run: git diff-files -p --exit-code --diff-filter=ADMR -w
